logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        dialect.storage_engine: innodb

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PROVIDER_URI}
          jwk-set-uri: ${PROVIDER_JWKS}
          audiences: ${AUDIENCES}

server:
  ssl:
    enabled: true
    key-store: ${KEY_LOCATION}
    key-store-password: ${KEY_PASSWORD}
    keyStoreType: ${KEY_TYPE}
    keyAlias: ${KEY_ALIAS}